global:
  scrape_interval: 15s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


# Example job for node_exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

# Example job for github_exporter
  - job_name: 'github'
    scrape_interval: 5m
    static_configs:
      - targets: ['github_exporter:9171']